# This is a basic workflow to help you get started with Actions

name: My-GitHubActions-Basics
on:
  push:
    branches: 
      - master
jobs:
  testing_level:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message in testing_level
        run: echo "Hello World from 'testing_level'"
        
      - name: Check aws-cli version
        run: aws --version
 
