# GitHub actions CI/CD pipeline to AWS.

name: My-GitHubActions-Basics
evn:
  ElasticBeanstalk_Package_S3: "blade-runner-pipeline"
  ElasticBeanstalk_AppName   : "Test-Pipeline"
  ElasticBeanstalk_EnvName   : "Test-Pipeline-Env"
  Deploy_Package_Name        : "test_pipeline_${{ github.sha }}.zip"
  AWS_REGION_NAME            : "eu-north-1"
  
# github.sha = The commit SHA that triggered the workflow run.

on:
  push:
    branches: 
      - master
jobs:
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git Clone our repo
        uses: actions/checkout@v1

# It is an official GitHub Action used to check-out a repository so a workflow can access it.
        
      - name: Create ZIP deployment package
        run: zip -r ${{ env.Deploy_Package_Name }} ./ -x *.git*
 
  ci_part:
    runs-on: ubuntu-latest
